Repository fermionprotocol/contracts, pull requests merged in 2025-03, with the labels that each got.

#327 Seaport integration test
  .solcover.js
  README.md
  test/integration/seaport.ts
Labels: v1.0.1

#384 Reorganise folder structure.
  contracts/diamond/facets/AccessController.sol
  contracts/diamond/facets/DiamondCutFacet.sol
  contracts/protocol/bases/mixins/Access.sol
  contracts/protocol/bases/mixins/Context.sol
  contracts/protocol/bases/mixins/Custody.sol
  contracts/protocol/bases/mixins/FundsManager.sol
  contracts/protocol/bases/mixins/ReentrancyGuard.sol
  contracts/protocol/clients/FermionBuyoutAuction.sol
  contracts/protocol/clients/FermionFNFT.sol
  contracts/protocol/clients/FermionFractions.sol
  contracts/protocol/clients/FermionFractionsMint.sol
  contracts/protocol/facets/Config.sol
  contracts/protocol/facets/Custody.sol
  contracts/protocol/facets/CustodyVault.sol
  contracts/protocol/facets/Entity.sol
  contracts/protocol/facets/Funds.sol
  contracts/protocol/facets/MetaTransaction.sol
  contracts/protocol/facets/Offer.sol
  contracts/protocol/facets/Pause.sol
  contracts/protocol/facets/PriceOracleRegistry.sol
  contracts/protocol/facets/Verification.sol
  contracts/protocol/libs/ContextLib.sol
  contracts/protocol/libs/EntityLib.sol
Labels: v1.1.0

#377 Renounce Self Account Role
  contracts/protocol/facets/Entity.sol
  test/protocol/entityFacet.ts
Labels: v1.1.0

#404 Start buyout auction if the vault balance falls under the liquidation threshold
  contracts/protocol/clients/FermionBuyoutAuction.sol
  contracts/protocol/facets/CustodyVault.sol
  contracts/protocol/interfaces/IFermionBuyoutAuction.sol
  contracts/protocol/libs/FermionFNFTLib.sol
  test/protocol/custodyVaultFacet.ts
Labels: enhancement, v1.1.0

#375 Epochs feature
  contracts/protocol/bases/mixins/FundsManager.sol
  contracts/protocol/clients/Common.sol
  contracts/protocol/clients/FermionBuyoutAuction.sol
  contracts/protocol/clients/FermionFNFT.sol
  contracts/protocol/clients/FermionFNFTPriceManager.sol
  contracts/protocol/clients/FermionFractions.sol
  contracts/protocol/clients/FermionFractionsERC20.sol
  contracts/protocol/clients/FermionFractionsERC20Base.sol
  contracts/protocol/clients/FermionFractionsMint.sol
  contracts/protocol/domain/Types.sol
  contracts/protocol/facets/CustodyVault.sol
  contracts/protocol/interfaces/IFermionFNFT.sol
  contracts/protocol/interfaces/IFermionFNFTPriceManager.sol
  contracts/protocol/interfaces/IFermionFractions.sol
  contracts/protocol/interfaces/events/IFermionFractionsEvents.sol
  contracts/protocol/libs/FermionFNFTLib.sol
  scripts/deploy.ts
  test/clients/fermionFNFT.ts
  test/clients/fermionFractions.ts
  test/clients/fermionWrapper.ts
  test/protocol/custodyVaultFacet.ts
  test/protocol/fundsFacet.ts
  test/utils/common.ts
  yarn.lock
Labels: v1.1.0

#373 Fermion royalties
  contracts/protocol/bases/mixins/Access.sol
  contracts/protocol/clients/Common.sol
  contracts/protocol/clients/CreatorToken.sol
  contracts/protocol/clients/FermionBuyoutAuction.sol
  contracts/protocol/clients/FermionFNFT.sol
  contracts/protocol/clients/FermionFractions.sol
  contracts/protocol/clients/FermionWrapper.sol
  contracts/protocol/clients/SeaportWrapper.sol
  contracts/protocol/domain/Errors.sol
  contracts/protocol/domain/Types.sol
  contracts/protocol/facets/Config.sol
  contracts/protocol/facets/Custody.sol
  contracts/protocol/facets/CustodyVault.sol
  contracts/protocol/facets/Entity.sol
  contracts/protocol/facets/Funds.sol
  contracts/protocol/facets/Offer.sol
  contracts/protocol/facets/Royalties.sol
  contracts/protocol/facets/Verification.sol
  contracts/protocol/interfaces/IFermionWrapper.sol
  contracts/protocol/interfaces/events/IConfigEvents.sol
  contracts/protocol/interfaces/events/IEntityEvents.sol
  contracts/protocol/interfaces/events/IOfferEvents.sol
  contracts/protocol/libs/EntityLib.sol
  contracts/protocol/libs/FermionFNFTLib.sol
  contracts/protocol/libs/RoyaltiesLib.sol
  contracts/protocol/libs/Storage.sol
  contracts/test/MockFermionProtocol.sol
  contracts/test/MockTransferValidator.sol
  contracts/test/TestMetaTransactions.sol
  fermion.config.ts
  package.json
  scripts/deploy.ts
  test/clients/fermionFNFT.ts
  test/clients/fermionFractions.ts
  test/clients/fermionWrapper.ts
  test/diamond/diamondTest.ts
  test/protocol/configFacet.ts
  test/protocol/custodyFacet.ts
  test/protocol/custodyVaultFacet.ts
  test/protocol/entityFacet.ts
  test/protocol/fundsFacet.ts
  test/protocol/metaTransactionFacet.ts
  test/protocol/offerFacet.ts
  test/protocol/royaltiesFacet.ts
  test/protocol/verificationFacet.ts
  test/utils/enums.ts
  test/utils/seaport.ts
  yarn.lock
Labels: v1.1.0

#399 Custody Period Check
  contracts/protocol/domain/Errors.sol
  contracts/protocol/facets/Offer.sol
  test/protocol/offerFacet.ts
Labels: v1.1.0

#402 Add verification metadata
  contracts/protocol/domain/Errors.sol
  contracts/protocol/domain/Types.sol
  contracts/protocol/facets/Offer.sol
  contracts/protocol/facets/Royalties.sol
  contracts/protocol/facets/Verification.sol
  contracts/protocol/interfaces/events/IVerificationEvents.sol
  contracts/protocol/libs/Storage.sol
  test/protocol/custodyFacet.ts
  test/protocol/custodyVaultFacet.ts
  test/protocol/entityFacet.ts
  test/protocol/fundsFacet.ts
  test/protocol/metaTransactionFacet.ts
  test/protocol/offerFacet.ts
  test/protocol/royaltiesFacet.ts
  test/protocol/verificationFacet.ts
  test/utils/enums.ts
Labels: enhancement, v1.1.0

#415 Migrate fractions
  contracts/protocol/clients/FermionFractions.sol
  contracts/protocol/clients/FermionFractionsMint.sol
  contracts/protocol/domain/Errors.sol
  contracts/protocol/domain/Types.sol
  contracts/protocol/interfaces/events/IFermionFractionsEvents.sol
  test/clients/fermionFractions.ts
Labels: v1.1.0

#409 Set fnft name and symbol while minting
  contracts/protocol/clients/FermionFNFT.sol
  contracts/protocol/domain/Types.sol
  contracts/protocol/facets/Offer.sol
  contracts/protocol/interfaces/IFermionFNFT.sol
  contracts/protocol/libs/FermionFNFTLib.sol
  test/clients/fermionFNFT.ts
  test/clients/fermionFractions.ts
  test/clients/fermionWrapper.ts
  test/protocol/custodyFacet.ts
  test/protocol/custodyVaultFacet.ts
  test/protocol/entityFacet.ts
  test/protocol/fundsFacet.ts
  test/protocol/metaTransactionFacet.ts
  test/protocol/offerFacet.ts
  test/protocol/royaltiesFacet.ts
  test/protocol/verificationFacet.ts
Labels: enhancement, v1.1.0

#414 ERC2771 support for metatransactions
  contracts/protocol/bases/mixins/FundsManager.sol
  contracts/protocol/clients/FermionBuyoutAuction.sol
  contracts/protocol/clients/FermionFractionsERC20.sol
  contracts/protocol/clients/FermionFractionsMint.sol
  contracts/protocol/facets/Custody.sol
  contracts/protocol/facets/CustodyVault.sol
  contracts/protocol/facets/Funds.sol
  contracts/protocol/facets/MetaTransaction.sol
  contracts/protocol/facets/Offer.sol
  contracts/protocol/facets/Verification.sol
  contracts/protocol/interfaces/IFermionFNFT.sol
  contracts/protocol/libs/FermionFNFTLib.sol
  contracts/test/TestMetaTransactions.sol
  scripts/deploy.ts
  test/clients/fermionFNFT.ts
  test/clients/fermionFractions.ts
  test/clients/fermionWrapper.ts
  test/protocol/metaTransactionFacet.ts
Labels: enhancement, v1.1.0

#430 safeTransfer for wrapped native
  contracts/protocol/clients/FermionFNFTBase.sol
  contracts/protocol/clients/FermionWrapper.sol
Labels: refactor

#431 Return entityId when creating entity
  contracts/protocol/facets/Entity.sol
Labels: v1.1.0

#435 FNFT immutable protocol address and ERC2771 fix
  contracts/protocol/clients/FermionBuyoutAuction.sol
  contracts/protocol/clients/FermionFNFT.sol
  contracts/protocol/clients/FermionFNFTBase.sol
  contracts/protocol/clients/FermionFNFTPriceManager.sol
  contracts/protocol/clients/FermionFractions.sol
  contracts/protocol/clients/FermionFractionsMint.sol
  contracts/protocol/clients/FermionWrapper.sol
  contracts/protocol/clients/SeaportWrapper.sol
  contracts/protocol/interfaces/IFermionFNFTPriceManager.sol
  contracts/test/TestMetaTransactions.sol
  scripts/deploy.ts
  test/clients/fermionFNFT.ts
  test/clients/fermionFractions.ts
  test/clients/fermionWrapper.ts
  test/protocol/metaTransactionFacet.ts
Labels: v1.1.0

#450 Fix misleading error field names
  contracts/protocol/domain/Errors.sol
Labels: v1.1.0
